---
- name: ensure pip is installed (apt)
  apt:
    name: python-pip
    state: present
  when: ansible_os_family == "Debian"

- name: ensure pip is installed (yum)
  yum:
    name: python-pip
    state: present
  when: ansible_os_family == "Redhat"

- name: install docker-py with python-pip
  pip:
    name: docker-py
    state: latest
# vim:ft=ansible:
