---
- name: include OS vars
  include_vars: "{{ ansible_os_family }}.yml"

- include: "{{ ansible_os_family }}.yml"

- include: dockerpy.yml
  when: has_dockerpy

- name: ensure docker is started and enabled
  service:
    name: docker
    enabled: yes
    state: started
# vim:ft=ansible:
