---
- name: ensure repo is present
  copy:
    src: repos/Centos-7
    dest: /etc/yum.repos.d/docker.repo

- name: ensure docker is installed
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ docker_packages }}"

# vim:ft=ansible:
