---
- name: Disable kernel debug
  lineinfile:
    line: "#MAKEDEBUG=yes"
    regexp: "^.*MAKEDEBUG=.*"
    dest: /etc/sysconfig/kernel
  notify:
    - "update grub2"
  when: >
    ansible_distribution == 'CentOS' and
    ansible_distribution_version >= 7.2

- meta: flush_handlers
# vim:ft=ansible:
