---
- name: Check in ansible if ansible_fqdn variable is correct
  fail:
    msg: "ansible_fqdn: {{ ansible_fqdn }}, but fqdn should be {{ inventory_hostname }}.{{ dns_domain }}"
  when: not dns_domain in ansible_fqdn

- name: Ensure hostname is the FQDN of the server
  hostname:
    name: "{{ ansible_fqdn }}"

- name: Set /etc/hosts to correct value
  lineinfile:
    dest: /etc/hosts
    state: present
    regexp: "^{{ lookup('dig', ansible_fqdn) }}.+{{ ansible_fqdn }}.+{{ ansible_hostname }}"
    line: "{{ lookup('dig', ansible_fqdn) }} {{ ansible_fqdn }} {{ ansible_hostname }} {{ ansible_hostname }}.bck{% for i in host_extradomains %} {{ i }}{% endfor %}"
    backup: yes

# vim:ft=ansible:

