---
- name: Install the required packages in Redhat derivatives
  yum:
    name: ntp
    state: "{{ ntp_pkg_state }}"
  when: ansible_os_family == 'RedHat'

- name: Install the required packages in Debian derivatives
  apt:
    name: ntp
    state: "{{ ntp_pkg_state }}"
  when: ansible_os_family == 'Debian'

- name: Copy the ntp.conf template file
  template:
    src: etc-ntp-conf.j2
    dest: /etc/ntp.conf
  notify:
  - ntpdate
  - restart ntp

- name: Enable ntp service
  service:
    name: "{{ ntp_service_name }}"
    enabled: "{{ ntp_service_enabled }}"

- meta: flush_handlers
# vim:ft=ansible:
