---
- name: FILL GENERIC MAP /etc/postfix/sender_canonical
  when: has_mail_management
  lineinfile: >
    state=present line="@{{ ansible_fqdn }} {{ smtp_source }}" create=yes
    dest=/etc/postfix/sender_canonical backup=yes regexp="^@{{ ansible_fqdn }}"
  notify:
  - postmap gen
  - restart postfix

- name: FILL ALIASES /etc/aliases
  when: has_mail_management
  lineinfile: >
    state=present line="root:                   {{ root_mail }}"
    dest=/etc/aliases backup=yes regexp='^root\:'
  notify:
  - newaliases

- name: TEMPLATE /etc/postfix/main.cf
  when: has_mail_management
  template: src=etc-postfix-main.cf.j2 dest=/etc/postfix/main.cf owner=root group=root mode=644 backup=yes
  notify:
  - restart postfix


- name: SERVICE enable + start
  when: has_mail_management
  service: name={{ postfix_service_name }} enabled=yes state=started

#- name: TEMPLATE /etc/aliases
# vim:ft=ansible:

