---
# NTP
ntp_pkg_state: 'installed'
ntp_service_state: 'started'
ntp_service_enabled: 'yes'
ntp_servers:
  - ntp.void
ntp_config_restrict:
  - '-4 default kod notrap nomodify nopeer noquery'
  - '-6 default kod notrap nomodify nopeer noquery'
  - '127.0.0.1'
  - '::1'
ntp_config_filegen:
  - 'loopstats file loopstats type day enable'
  - 'peerstats file peerstats type day enable'
  - 'clockstats file clockstats type day enable'
ntp_config_statistics: 'loopstats peerstats clockstats'
is_ntp_server: false

# DNS
is_dns_server: false
is_dnsmasq_cache: false
dns_domain: void
dns_servers:
  - 8.8.8.8
dns_search:
  - void
dns_options:
  - 'rotate'
  - 'timeout:2'
  - 'attempts:2'

# SNMPD
snmpd_communities:
  - defaultpublic
snmpd_location: 'defaultlocation'
snmpd_syscontact: 'defaultsyscontact'

# VMWARE
ovmt_service_name: 'vmtoolsd'

# TIMEZONE
timezone: "Etc/UTC"

# HOSTS
host_extradomains: []

# PACKAGES
base_debian_packages:
  - curl
  - dnsutils
  - elinks
  - git
  - htop
  - mailutils
  - mlocate
  - mtr-tiny
  - nmap
  - postfix
  - screen
  - tmux
  - tree
  - tzdata
  - unzip
  - update-motd
  - update-notifier-common
  - vim
  - whois
  - zip
  - zsh

base_redhat_packages:
  - bind-utils
  - curl
  - elinks
  - git
  - htop
  - ipa-client
  - mailx
  - mlocate
  - mtr
  - nmap
  - postfix
  - screen
  - tmux
  - tree
  - tzdata
  - unzip
  - vim
  - zip
  - zsh

# vim:ft=ansible:
